<?php
/**
 * PartnerOrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 4
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\OrdersV4;

/**
 * PartnerOrderTest Class Doc Comment
 *
 * @category    Class
 * @description PartnerOrder
 * @package     EzzeSiftuz\OrdersV4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartnerOrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PartnerOrder"
     */
    public function testPartnerOrder()
    {
    }

    /**
     * Test attribute "sales_order_id"
     */
    public function testPropertySalesOrderId()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "order_date"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "position_items"
     */
    public function testPropertyPositionItems()
    {
    }

    /**
     * Test attribute "order_lifecycle_information"
     */
    public function testPropertyOrderLifecycleInformation()
    {
    }

    /**
     * Test attribute "initial_delivery_fees"
     */
    public function testPropertyInitialDeliveryFees()
    {
    }

    /**
     * Test attribute "initial_discounts"
     */
    public function testPropertyInitialDiscounts()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "invoice_address"
     */
    public function testPropertyInvoiceAddress()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }
}
