<?php
/**
 * AllApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 4
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\OrdersV4;

use EzzeSiftuz\OrdersV4\Configuration;
use EzzeSiftuz\OrdersV4\ApiException;
use EzzeSiftuz\OrdersV4\ObjectSerializer;

/**
 * AllApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AllApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelPartnerOrderPositionItems
     *
     * Cancel specific position items of an order.
     *
     */
    public function testCancelPartnerOrderPositionItems()
    {
    }

    /**
     * Test case for cancelPartnerOrders
     *
     * Cancel all position items of an order.
     *
     */
    public function testCancelPartnerOrders()
    {
    }

    /**
     * Test case for findPartnerOrders
     *
     * List of orders filtered by fulfillment state.
     *
     */
    public function testFindPartnerOrders()
    {
    }

    /**
     * Test case for getPartnerOrderByOrderNumber
     *
     * Get an order via order number.
     *
     */
    public function testGetPartnerOrderByOrderNumber()
    {
    }

    /**
     * Test case for getPartnerOrderBySalesOrderId
     *
     * Get an order via sales order id.
     *
     */
    public function testGetPartnerOrderBySalesOrderId()
    {
    }
}
